services:
  backend:
    build:
      context: .
    container_name: backend-app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules # evitar conflicto con node_modules del host
    environment:
      - NODE_ENV=development
      - DOTENV_CONFIG_PATH=/app/.env
    command: npm run dev
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: back-postgres-1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tolisto
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
